In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import tensorflow as tf
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Import our input dataset
ELA_df = pd.read_csv('../Data/ELA_data_1819_clean.csv')
ELA_df = pd.DataFrame(ELA_df)

In [2]:
ELA_df.dtypes

Student                 int64
previous scale score    int64
Diagnostic 1            int64
GM 1                    int64
GM 2                    int64
Diagnostic 2            int64
acheivement level       int64
dtype: object

In [3]:
#drop null values
ELA_df.dropna(axis=0)

,Student,previous scale score,Diagnostic 1,GM 1,GM 2,Diagnostic 2,acheivement level
0,65,269,453,446,388,386,1
1,51,292,416,486,478,475,1
2,64,274,513,529,515,522,1
3,67,274,494,486,486,428,1
4,3,284,493,472,532,516,1
...,...,...,...,...,...,...,...
72,26,341,621,611,630,630,4
73,29,339,609,589,642,611,4
74,47,329,595,605,605,630,4
75,24,342,637,617,634,639,5
76,16,338,645,656,677,651,5

In [4]:
#create target and features
X = ELA_df.drop(columns = ['Student', 'acheivement level'])
y = ELA_df['acheivement level']

#split training/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [5]:
# create a random forest classifier
rf_model = RandomForestClassifier(n_estimators=128, random_state=42)

#fit the model
rf_model = rf_model.fit(X_train, y_train)

# evaluate the model
y_pred = rf_model.predict(X_test)
print(f' Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}')

 Random forest predictive accuracy: 0.650

In [6]:
#generate a confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["Actual 1", "Actual 2","Actual 3","Actual 4","Actual 5"],
    columns=["Predicted 1", "Predicted 2","Predicted 3","Predicted 4","Predicted 5" ]
)
display(cm_df)

          Predicted 1  Predicted 2  Predicted 3  Predicted 4  Predicted 5
Actual 1            3            0            1            0            0
Actual 2            0            2            3            1            0
Actual 3            0            1            4            1            0
Actual 4            0            0            0            3            0
Actual 5            0            0            0            0            1